### ISSUE TITLE
Read the Docs + badge

### ISSUE THREAD

**Issue by ramnes** [numberly/thingy#5]

**Comment by ramnes** [comment]
Also, we should include in the documentation a comparison with other similar tools: AttrDict, Bunch, Munch, Addict, etc.

**Comment by trubesv** [comment]
Concerning RTFD, I emailed them regarding the name conflict with [this project](https://readthedocs.org/projects/thingy). Let's hope for a positive outcome :)

I will setup the hosting and the badge once we have a definite answer.

**Comment by ramnes** [comment]
:pray:

**Comment by trubesv** [comment]
Our prayers have not been answered:

> I've got a reply from Thingy saying that they registered that namespace because they will use it when they release a version -they are curreently in alpha.
Seems to be a legitimate user and project and they reply in time. So, I think there isn't too much here that we can do.
Manuel from Read the Docs

**Comment by Bennyelg** [comment]
I'll suggest change the name, instead Thingy to NamedDict

**Comment by ramnes** [comment]
Renaming would indeed fix the problem.

Althought, "NamedDict" reminds me a lot `namedtuple`, that behaves and is used very differently, so I'm not to keen on that one.

Maybe we could rather simply add a `python-` prefix just for the documentation URL (python-thingy.readthedocs.io)? It's not perfect but it's simple and will do it until we decide to change the project name, if we do.

**Comment by ramnes** [comment]
ping @trubesv

**Comment by ramnes** [comment]
@trubesv can we move forward with `python-thingy`, please?

**Comment by trubesv** [comment]
https://python-thingy.readthedocs.io/

Done :pray:
